selectors in dashboard
truera/trulens pull request #261
Opened 2023-07-01 00:13 UTC by piotrm0

Displaying selectors (used for specifying on feedback functions are evaluated) in the dashboard. Not all subcomponents are covered presently. Examples (notice the green text):

![Screenshot 2023-06-30 at 17 11 48](https://github.com/truera/trulens/assets/421701/f60be3e8-cd1b-4c44-8364-251b9ce91901)
![Screenshot 2023-06-30 at 17 11 37](https://github.com/truera/trulens/assets/421701/a0a58ea8-84ef-471f-bc6f-d9048c2c8473)
![Screenshot 2023-06-30 at 17 11 29](https://github.com/truera/trulens/assets/421701/0f4f219a-7ba1-428f-a09e-81565c755225)

2023-07-03 14:31 UTC, rshih32 requested changes

2023-07-11 20:38 UTC, piotrm0 commented on trulens_eval/trulens_eval/feedback.py
removed the other PR stuff

2023-07-12 13:59 UTC, rshih32 approved these changes

2023-07-12 17:49 UTC, rshih32 approved these changes

2023-07-12 17:52 UTC, merged