rebatch for attributions
truera/trulens pull request #69
Opened 2022-04-01 23:07 UTC by piotrm0

Moves tiling of model inputs to attribution methods instead of fprop in model wrappers. Adds a new `rebatch_size` parameter to attribution constructors to rebatch instances for handling larger models in gpu memory. This parameter has been added to the memory suggestions context as in this example message:

```
OutOfMemory: Ran out of memory ({'device': 'cuda:1'}). Consider reducing memory-impactful parameters.
	float size = 4 (torch.float32); consider changing to a smaller type.
	batch size = 4; consider reducing the size of the batch you send to the attributions method.
	distribution of interest size = 1000; consider reducing intervention resolution.
	combined batch size = 4000; consider reducing batch size, intervention size
	rebatch_size = 900; consider reducing this AttributionMethod constructor parameter (default is same as combined batch size).
```

Changing `rebatch_size` to something smaller in this case allows the attribution to compute fine.

2022-04-04 21:01 UTC, rshih32 requested changes

2022-04-05 00:26 UTC, piotrm0 commented on trulens/nn/attribution.py
> +        intervention = ModelInputs(args=D, kwargs={})
This is currently internal so the "ModelInputs" name might not be too problematic even for cases where it is not the model inputs. Any name suggestions?

Rebatching does not apply just to doi as as the case discussed earlier. Now rebatching can split a single user batch into multiple batches as well so I don't think the rebatch_doi name is appropriate.

2022-04-05 00:27 UTC, piotrm0 commented on notebooks/cuda/memtest_pytorch.ipynb
> +{
Purposely not put that into notebook tests since cuda is required. Can CI run on a computer with a cuda enabled GPU?

2022-04-05 12:14 UTC, rshih32 commented on trulens/nn/attribution.py
> +        intervention = ModelInputs(args=D, kwargs={})
for the first item: you have the InterventionLike type for the typing. even if internal, we want the next developers to not get confused or misinterpret.

second item: so its both rebatching model inputs and the intervention. the parameter name - rebatch_size is fine, in the docs explain that it rebatches the inputs and the intervention for memory reasons. and that doi is the cause,etc,etc. An example
change 
```
Will rebatch model inputs to this size if given  
```
to
```
A parameter used to optimize gpu memory usage for attributions. Typically used when a DoI has many values. Many valued DoIs will expand the tensors sent to each layer to original_batch_size * doi_size. The rebatch size will break up original_batch_size * doi_size into rebatch_size chunks to send to gpu.
```

then the internal

2022-04-08 18:29 UTC, piotrm0 commented on trulens/nn/attribution.py
> +                Will rebatch model inputs to this size if given.
Done.

2022-04-08 18:29 UTC, piotrm0 commented on trulens/nn/attribution.py
> +        intervention = ModelInputs(args=D, kwargs={})
Done.

2022-04-08 18:37 UTC, piotrm0 commented on trulens/nn/backend/__init__.py
> +def rebatch_model_inputs(
Done.

2022-04-08 18:38 UTC, piotrm0 commented on trulens/nn/attribution.py
> +        intervention = ModelInputs(args=D, kwargs={})
Done.

2022-04-12 21:03 UTC, rshih32 approved these changes

2022-04-12 22:19 UTC, merged