fix: italise TruLens-Eval ref
truera/trulens pull request #997
Opened 2024-03-13 10:17 UTC by markdavidmc0

Small change - first contribution modifying the README. One liner.

2024-03-14 22:15 UTC, piotrm0 commented
Thanks; can you also add this as a suggestion to proper names formatting in `[trulens](https://github.com/truera/trulens/tree/bb11c2d9ee3879b5f9455f7a6ba6a79424da6f9b)/[docs](https://github.com/truera/trulens/tree/bb11c2d9ee3879b5f9455f7a6ba6a79424da6f9b/docs)/[trulens_eval](https://github.com/truera/trulens/tree/bb11c2d9ee3879b5f9455f7a6ba6a79424da6f9b/docs/trulens_eval)/[contributing](https://github.com/truera/trulens/tree/bb11c2d9ee3879b5f9455f7a6ba6a79424da6f9b/docs/trulens_eval/contributing)
/standards.md`

2024-03-14 23:57 UTC, joshreini1 approved these changes

2024-03-15 00:00 UTC, joshreini1 commented
Sorry, approved too fast. Changes to `README.md` and `trulens_eval/README.md` need to be made to `gh_top_intro.md` and `intro.md`  respectively. These files will overwrite the READMEs.

2024-03-15 00:01 UTC, joshreini1 requested changes
Please mirror changes in `intro.md`

2024-03-16 20:30 UTC, markdavidmc0 commented
Happy with changes inverted commas -> italics in `/docs/trulens_eval/contributing/standards.md` as well?

2024-03-18 12:25 UTC, joshreini1 approved these changes

2024-03-22 22:07 UTC, joshreini1 commented
@piotrm0 seems the eval test here gets skipped but the validation hangs, do you know how to fix?

2024-03-26 22:01 UTC, merged